Updating dockerfile

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -66,6 +66,8 @@ jobs:
         run: |
           cd backend
           npm run build
+          echo "Build output:"
+          ls -la .medusa/ || echo ".medusa not found"
 #       SKIP LINTING TEMPORARILY
 #      - name: Linter check
 #        shell: bash
@@ -144,7 +146,7 @@ jobs:
         uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
 
       - name: Build Docker image
-        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6
+        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
         with:
           context: .
           push: false
